### ISSUE TITLE
Cross platform builds

### ISSUE THREAD

**Issue by roshanr95** [aws/aws-nitro-enclaves-sdk-bootstrap#35]
Getting arch from `pkgs.stdenv.hostPlatform.uname.processor` makes it hard to do cross platform builds. A quick fix would be to take it as input in the derivations (like `pkgs` currently) and use the above as the default value. That way, consumers can pass in different archs and pkgs and cross build.

**Comment by foersleo** [comment]
Hi @roshanr95,

you are right about that. The reasoning why I did choose to not include this for cross-platform builds is that I believe the native build and the cross-build are not going to be identical. I have not checked that, but I believe that should be the case given different tool chains used to produce each of them.

If that assumption is correct, then arguing about builds being the same, produced from the same source/definition becomes more of a head ache.

I have an item to explore if this is something that can be solved easily, but I did not have time to get around to this.

**Comment by roshanr95** [comment]
Makes sense. The way I usually do my cross builds is using Qemu and `--system` on Nix, especially if reproducibility is important.

**Comment by sveith** [comment]
Cross-compilation support has been implemented as part of https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/pull/39.

It can be used by instantiating nixpkgs as appropriate for the desired host platform, and passing it as the `pkgs` parameter accepted by the top-level derivation, like so:

```
$ uname --machine
x86_64
$ nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
/nix/store/gpxqr7gbm3029dwvjc1075692nbzvn1d-enclaves-blobs-aarch64
$ tree result
result
└── aarch64
    ├── Image
    ├── Image.config
    ├── init
    ├── linuxkit
    └── nsm.ko

1 directory, 5 files
$ file result/aarch64/init 
result/aarch64/init: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
```

Note that currently, the produced binaries are still different between native and cross-compiled builds, exactly as @foersleo suspected previously.

**Comment by roshanr95** [comment]
As I mentioned above, I build cross-platform using qemu, which usually gives the same binaries as native builds (albeit _veeery_ slow). It's quite simple to set up (on linux anyway) via https://github.com/tonistiigi/binfmt. In Nix, you have to set the system correctly (e.g. using `--system` with a flake) and pass in the right nixpkgs (e.g. using `nixpkgs.${system}.pkgs` with a flake). Can confirm that it gives the same binaries for the kernel builds as well and furthermore, it matches the artifacts from before this PR as well.

Just leaving this here in case people are looking for identical cross platform builds and don't mind the performance hit.
