### ISSUE TITLE
Low entropy after boot (reading from /dev/random blocks)

### ISSUE THREAD

**Issue by ppmag** [aws/aws-nitro-enclaves-sdk-bootstrap#5]
Hi,

I just faced the problem, brand new enclave has zero entropy:
```
cat /proc/sys/kernel/random/entropy_avail
0
```

which cause block when reading from  `/dev/random` early after boot.

What about adding some entropy from NSM RNG at boot stage?
Another question: which preferred workaround to use right now?

**Comment by andraprs** [comment]
Options for getting entropy were shared in https://github.com/aws/aws-nitro-enclaves-sdk-c/issues/41. Closing this issue as well, as it is the same topic.
